name: Future
on:
  push:
    branches:
      - future
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install prereqs
      run: sudo apt install -y awscli npm
    - name: Build
      run: npm run build
    - name: Upload to S3
      run: aws s3 sync build/ s3://$URL/ --delete
      env:
        URL: ${{ secrets.URL_FUTURE }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Set no-cache on the service worker
      run: aws s3 cp s3://$URL/service-worker.js s3://$URL/service-worker.js --metadata-directive REPLACE --cache-control no-cache
      env:
        URL: ${{ secrets.URL_FUTURE }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Invalidate Cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID_FUTURE }}
